# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/distributedML.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/distributedML.proto',
  package='distributedML',
  syntax='proto3',
  serialized_pb=_b('\n\x1aprotos/distributedML.proto\x12\rdistributedML\"`\n\tSubTensor\x12\x12\n\ntensor_len\x18\x01 \x01(\x05\x12\x14\n\x0ctensor_chunk\x18\x02 \x01(\x05\x12\x16\n\x0etensor_content\x18\x03 \x01(\x0c\x12\x11\n\tdata_indx\x18\x04 \x01(\x05\"\x1f\n\nWorkerInfo\x12\x11\n\tworker_id\x18\x01 \x01(\x05\"\x1c\n\nStatusCode\x12\x0e\n\x06status\x18\x01 \x01(\x05\"6\n\tPrevBatch\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x12\x16\n\x0eprev_data_indx\x18\x02 \x01(\x05\"1\n\tNextBatch\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x12\x11\n\tdata_indx\x18\x02 \x01(\x05\"\x07\n\x05\x65mpty2\x98\x02\n\x0bParamFeeder\x12\x45\n\nSendParams\x12\x19.distributedML.WorkerInfo\x1a\x18.distributedML.SubTensor\"\x00\x30\x01\x12\x45\n\rSendNextBatch\x12\x18.distributedML.PrevBatch\x1a\x18.distributedML.NextBatch\"\x00\x12\x45\n\nGetUpdates\x12\x18.distributedML.SubTensor\x1a\x19.distributedML.StatusCode\"\x00(\x01\x12\x34\n\x04ping\x12\x14.distributedML.empty\x1a\x14.distributedML.empty\"\x00\x62\x06proto3')
)




_SUBTENSOR = _descriptor.Descriptor(
  name='SubTensor',
  full_name='distributedML.SubTensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor_len', full_name='distributedML.SubTensor.tensor_len', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tensor_chunk', full_name='distributedML.SubTensor.tensor_chunk', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tensor_content', full_name='distributedML.SubTensor.tensor_content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_indx', full_name='distributedML.SubTensor.data_indx', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=141,
)


_WORKERINFO = _descriptor.Descriptor(
  name='WorkerInfo',
  full_name='distributedML.WorkerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='distributedML.WorkerInfo.worker_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=174,
)


_STATUSCODE = _descriptor.Descriptor(
  name='StatusCode',
  full_name='distributedML.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='distributedML.StatusCode.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=204,
)


_PREVBATCH = _descriptor.Descriptor(
  name='PrevBatch',
  full_name='distributedML.PrevBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='distributedML.PrevBatch.worker_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prev_data_indx', full_name='distributedML.PrevBatch.prev_data_indx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=260,
)


_NEXTBATCH = _descriptor.Descriptor(
  name='NextBatch',
  full_name='distributedML.NextBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='distributedML.NextBatch.worker_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_indx', full_name='distributedML.NextBatch.data_indx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=311,
)


_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='distributedML.empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=320,
)

DESCRIPTOR.message_types_by_name['SubTensor'] = _SUBTENSOR
DESCRIPTOR.message_types_by_name['WorkerInfo'] = _WORKERINFO
DESCRIPTOR.message_types_by_name['StatusCode'] = _STATUSCODE
DESCRIPTOR.message_types_by_name['PrevBatch'] = _PREVBATCH
DESCRIPTOR.message_types_by_name['NextBatch'] = _NEXTBATCH
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubTensor = _reflection.GeneratedProtocolMessageType('SubTensor', (_message.Message,), dict(
  DESCRIPTOR = _SUBTENSOR,
  __module__ = 'protos.distributedML_pb2'
  # @@protoc_insertion_point(class_scope:distributedML.SubTensor)
  ))
_sym_db.RegisterMessage(SubTensor)

WorkerInfo = _reflection.GeneratedProtocolMessageType('WorkerInfo', (_message.Message,), dict(
  DESCRIPTOR = _WORKERINFO,
  __module__ = 'protos.distributedML_pb2'
  # @@protoc_insertion_point(class_scope:distributedML.WorkerInfo)
  ))
_sym_db.RegisterMessage(WorkerInfo)

StatusCode = _reflection.GeneratedProtocolMessageType('StatusCode', (_message.Message,), dict(
  DESCRIPTOR = _STATUSCODE,
  __module__ = 'protos.distributedML_pb2'
  # @@protoc_insertion_point(class_scope:distributedML.StatusCode)
  ))
_sym_db.RegisterMessage(StatusCode)

PrevBatch = _reflection.GeneratedProtocolMessageType('PrevBatch', (_message.Message,), dict(
  DESCRIPTOR = _PREVBATCH,
  __module__ = 'protos.distributedML_pb2'
  # @@protoc_insertion_point(class_scope:distributedML.PrevBatch)
  ))
_sym_db.RegisterMessage(PrevBatch)

NextBatch = _reflection.GeneratedProtocolMessageType('NextBatch', (_message.Message,), dict(
  DESCRIPTOR = _NEXTBATCH,
  __module__ = 'protos.distributedML_pb2'
  # @@protoc_insertion_point(class_scope:distributedML.NextBatch)
  ))
_sym_db.RegisterMessage(NextBatch)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'protos.distributedML_pb2'
  # @@protoc_insertion_point(class_scope:distributedML.empty)
  ))
_sym_db.RegisterMessage(empty)



_PARAMFEEDER = _descriptor.ServiceDescriptor(
  name='ParamFeeder',
  full_name='distributedML.ParamFeeder',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=323,
  serialized_end=603,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendParams',
    full_name='distributedML.ParamFeeder.SendParams',
    index=0,
    containing_service=None,
    input_type=_WORKERINFO,
    output_type=_SUBTENSOR,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendNextBatch',
    full_name='distributedML.ParamFeeder.SendNextBatch',
    index=1,
    containing_service=None,
    input_type=_PREVBATCH,
    output_type=_NEXTBATCH,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUpdates',
    full_name='distributedML.ParamFeeder.GetUpdates',
    index=2,
    containing_service=None,
    input_type=_SUBTENSOR,
    output_type=_STATUSCODE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='distributedML.ParamFeeder.ping',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARAMFEEDER)

DESCRIPTOR.services_by_name['ParamFeeder'] = _PARAMFEEDER

# @@protoc_insertion_point(module_scope)
